### ISSUE TITLE
Getting error when running script with germany cities

### ISSUE THREAD

**Issue by regii** [tupton/python-yahoo-weather#7]
how to reproduce:
./weather.py 650272 -l
(City: Frankfurt, Germany)

Error:
Traceback (most recent call last):
  File "./weather.py", line 244, in <module>
    main(sys.argv[1:])
  File "./weather.py", line 225, in main
    weather = get_weather(args.location_code, args)
  File "./weather.py", line 51, in get_weather
    yunits = dom.getElementsByTagNameNS(WEATHER_NS, 'units')[0]
IndexError: list index out of range

**Comment by tupton** [comment]
That is an unfortunately misleading error. Apparently the postal code "650272" is not valid for Yahoo weather. Yahoo uses a different system of "location codes" for non-U.S. cities, which is extremely annoying.

I looked up the Frankfurt location code using https://weather.codes/search/?q=frankfurt.

I'll look into making this error a little bit better and more indicative of the fact that the given location code was invalid according to Yahoo.

**Comment by tupton** [comment]
An even better solution would be to use a locale-aware weather service and let the user provide that locale and be able to use their own local postal code...

**Comment by regii** [comment]
with GMXX0040 it is working. thx
